# Generated by Django 5.1.1 on 2026-10-04 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0006_remove_userscope_userscope_unique_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Référence')),
                ('type_alerte', models.CharField(choices=[('SEUIL_MIN', 'Seuil minimum dépassé'), ('SEUIL_MAX', 'Seuil maximum dépassé'), ('ANOMALIE_IA', 'Anomalie IA (réservé)')], default='SEUIL_MAX', max_length=20, verbose_name="Type d'alerte")),
                ('niveau', models.CharField(choices=[('INFORMATION', 'Information'), ('MINEURE', 'Mineure'), ('MAJEURE', 'Majeure'), ('CRITIQUE', 'Critique')], default='MINEURE', max_length=20, verbose_name='Niveau')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acquittée'), ('RESOLVED', 'Résolue')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('valeur', models.FloatField(verbose_name='Valeur mesurée')),
                ('seuil', models.FloatField(verbose_name='Seuil concerné')),
                ('unite', models.CharField(blank=True, default='', max_length=50, verbose_name='Unité')),
                ('depassement', models.FloatField(default=0.0, help_text='Écart absolu entre la valeur mesurée et le seuil franchi.', verbose_name='Dépassement (valeur − seuil)')),
                ('ratio_plage_pct', models.FloatField(default=0.0, help_text='(valeur − seuil) / (seuil_max − seuil_min) × 100.', verbose_name='Dépassement en % de la plage du capteur')),
                ('message', models.TextField(verbose_name='Message')),
                ('anomalie_ia_score', models.FloatField(blank=True, null=True, verbose_name="Score d'anomalie IA (réservé)")),
                ('nb_occurrences', models.PositiveIntegerField(default=1, verbose_name="Nombre d'occurrences")),
                ('derniere_valeur', models.FloatField(default=0.0, verbose_name='Dernière valeur mesurée')),
                ('derniere_occurrence', models.DateTimeField(verbose_name='Dernière occurrence')),
                ('date_declenchement', models.DateTimeField(verbose_name='Déclenchée le')),
                ('date_acquittement', models.DateTimeField(blank=True, null=True, verbose_name='Acquittée le')),
                ('commentaire_acquittement', models.TextField(blank=True, default='', verbose_name="Commentaire d'acquittement")),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Résolue le')),
                ('message_resolution', models.TextField(blank=True, default='', verbose_name='Motif de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquittee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL, verbose_name='Acquittée par')),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='equipements.sensor', verbose_name='Capteur')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='equipements.reading', verbose_name="Mesure à l'origine")),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='equipements.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_declenchement', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ALERTE_CREEE', 'Alerte créée'), ('ESCALADE', 'Alerte aggravée'), ('RETOUR_NORMALE', 'Retour à la normale'), ('INFO', 'Information')], default='ALERTE_CREEE', max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('niveau', models.CharField(choices=[('INFORMATION', 'Information'), ('MINEURE', 'Mineure'), ('MAJEURE', 'Majeure'), ('CRITIQUE', 'Critique')], default='INFORMATION', max_length=20, verbose_name='Niveau')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Lue le')),
                ('alerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alertes.alerte', verbose_name='Alerte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app', models.BooleanField(default=True, verbose_name='Notifications In-App')),
                ('email', models.BooleanField(default=False, help_text="Ignoré si aucun SMTP n'est configuré dans l'environnement.", verbose_name='Notifications par email')),
                ('sms', models.BooleanField(default=False, help_text='Canal préparé mais non activé : Twilio est optionnel.', verbose_name='Notifications par SMS (Twilio)')),
                ('email_destination', models.EmailField(blank=True, default='', help_text="Vide → l'email de l'utilisateur est utilisé.", max_length=254, verbose_name='Adresse email de destination')),
                ('niveau_min_email', models.CharField(choices=[('INFORMATION', 'Information'), ('MINEURE', 'Mineure'), ('MAJEURE', 'Majeure'), ('CRITIQUE', 'Critique')], default='MAJEURE', max_length=20, verbose_name="Niveau minimum pour l'email")),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_notification', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['statut', '-date_declenchement'], name='alerte_statut_date_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['machine', 'statut'], name='alerte_machine_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['capteur', 'statut'], name='alerte_capteur_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['niveau'], name='alerte_niveau_idx'),
        ),
        migrations.AddConstraint(
            model_name='alerte',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['ACTIVE', 'ACKNOWLEDGED'])), fields=('capteur', 'type_alerte'), name='alerte_unique_ouverte_par_capteur'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'lue'], name='notif_user_lue_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'alerte', 'type'), name='notification_unique_par_alerte_type'),
        ),
    ]
