# Generated by Django 5.1.1 on 2026-10-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigneProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Ligne de production',
                'verbose_name_plural': 'Lignes de production',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Usine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usine',
                'verbose_name_plural': 'Usines',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('identifiant_interne', models.CharField(max_length=100, unique=True)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('marque', models.CharField(blank=True, default='', max_length=100)),
                ('modele', models.CharField(blank=True, default='', max_length=100)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('position_sur_plan', models.CharField(blank=True, default='', max_length=200)),
                ('statut', models.CharField(choices=[('NORMAL', 'Normal'), ('DEGRADE', 'Dégradé'), ('CRITIQUE', 'Critique'), ('HORS_LIGNE', 'Hors ligne')], default='NORMAL', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='machines/photos/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='equipements.ligneproduction')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('MANUEL', 'Manuel'), ('FICHE_TECHNIQUE', 'Fiche technique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('fichier', models.FileField(upload_to='machines/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='equipements.machine')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('numero_piece', models.CharField(blank=True, default='', max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='equipements.machine')),
            ],
            options={
                'verbose_name': 'Composant',
                'verbose_name_plural': 'Composants',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('usine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='equipements.usine')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='ligneproduction',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='equipements.zone'),
        ),
    ]
