# Generated by Django 5.1.1 on 2026-10-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100, unique=True, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du capteur')),
                ('type_capteur', models.CharField(choices=[('TEMPERATURE', 'Température'), ('VIBRATION', 'Vibration'), ('PRESSION', 'Pression'), ('COURANT', 'Courant'), ('VITESSE_RPM', 'Vitesse (RPM)'), ('DEBIT', 'Débit'), ('NIVEAU_SONORE', 'Niveau sonore')], max_length=30, verbose_name='Type de capteur')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité de mesure')),
                ('frequence_mesure', models.IntegerField(help_text='Fréquence en secondes', verbose_name='Fréquence de mesure (secondes)')),
                ('seuil_min', models.FloatField(verbose_name='Seuil minimum')),
                ('seuil_max', models.FloatField(verbose_name='Seuil maximum')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='equipements.machine', verbose_name='Machine associée')),
            ],
            options={
                'verbose_name': 'Capteur',
                'verbose_name_plural': 'Capteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(verbose_name='Valeur mesurée')),
                ('timestamp', models.DateTimeField(verbose_name='Date et heure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hors_plage', models.BooleanField(default=False, verbose_name='Hors plage (min/max)')),
                ('est_valide', models.BooleanField(default=True, verbose_name='Lecture valide')),
                ('interpolation', models.BooleanField(default=False, verbose_name='Valeur interpolée')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='equipements.sensor', verbose_name='Capteur')),
            ],
            options={
                'verbose_name': 'Lecture de capteur',
                'verbose_name_plural': 'Lectures de capteurs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='equipements_sensor__6ac822_idx'), models.Index(fields=['timestamp'], name='equipements_timesta_f75073_idx')],
            },
        ),
    ]
