# Generated by Django 5.1.1 on 2026-10-03 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_sensor_reading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionVisuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/images/', verbose_name='Image inspectée')),
                ('date_inspection', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inspection")),
                ('statut_analyse', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_ANALYSE', 'En analyse'), ('TERMINEE', 'Terminée'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20, verbose_name="Statut de l'analyse")),
                ('resultat_analyse', models.JSONField(blank=True, null=True, verbose_name="Résultat de l'analyse")),
                ('score_confiance', models.FloatField(blank=True, null=True, verbose_name='Score de confiance')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('erreur_message', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipements.machine', verbose_name='Machine inspectée')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inspection visuelle',
                'verbose_name_plural': 'Inspections visuelles',
                'ordering': ['-date_inspection'],
                'indexes': [models.Index(fields=['machine', '-date_inspection'], name='equipements_machine_894626_idx'), models.Index(fields=['statut_analyse'], name='equipements_statut__c045d9_idx')],
            },
        ),
    ]
