# Generated by Django 5.1.1 on 2026-10-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_inspectionvisuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionvisuelle',
            name='confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Score de confiance (0-1)'),
        ),
        migrations.AddField(
            model_name='inspectionvisuelle',
            name='defect_detected',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Défaut détecté'),
        ),
        migrations.AddField(
            model_name='inspectionvisuelle',
            name='defect_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Type de défaut'),
        ),
        migrations.AddField(
            model_name='inspectionvisuelle',
            name='observation',
            field=models.TextField(blank=True, default='', verbose_name="Observation de l'analyse"),
        ),
    ]
