# Generated by Django 5.1.1 on 2026-10-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0004_inspectionvisuelle_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='equipements.ligneproduction', verbose_name='Ligne de production')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='equipements.machine', verbose_name='Machine')),
                ('usine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='equipements.usine', verbose_name='Usine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='equipements.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': "Périmètre d'accès",
                'verbose_name_plural': "Périmètres d'accès",
                'ordering': ['utilisateur', 'usine', 'zone', 'ligne', 'machine'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ligne__isnull', True), ('machine__isnull', True), ('usine__isnull', False), ('zone__isnull', True)), models.Q(('ligne__isnull', True), ('machine__isnull', True), ('usine__isnull', True), ('zone__isnull', False)), models.Q(('ligne__isnull', False), ('machine__isnull', True), ('usine__isnull', True), ('zone__isnull', True)), models.Q(('ligne__isnull', True), ('machine__isnull', False), ('usine__isnull', True), ('zone__isnull', True)), _connector='OR'), name='userscope_exactly_one_target'), models.CheckConstraint(condition=models.Q(('usine__isnull', False), ('zone__isnull', False), ('ligne__isnull', False), ('machine__isnull', False), _connector='OR'), name='userscope_at_least_one_target'), models.UniqueConstraint(fields=('utilisateur', 'usine', 'zone', 'ligne', 'machine'), name='userscope_unique_target')],
            },
        ),
    ]
