# Generated by Django 5.1.1 on 2026-10-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0005_userscope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userscope',
            name='userscope_unique_target',
        ),
    ]
